/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package window;

import algorithms.Euclides;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author swords
 */
public class EuclidesGui extends javax.swing.JFrame{
    int a;
    int b;
    int mod = -1;
    int aux = -1;
    Euclides euclides = new Euclides();
    /**
     * Creates new customizer Euclides
     */
    public EuclidesGui() {
        initComponents();
        
        Toolkit tolToolkit = getToolkit();
        Dimension size = tolToolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2-getHeight()/2);
        setSize(700,530);
        setResizable(false);
        initialize();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasEuclides = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructions = new javax.swing.JTextPane();
        switchToDijkstra = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        variables = new javax.swing.JTextField();
        addbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextArea();
        Limpiar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1453, 793));
        setLayout(null);

        canvasEuclides.setBackground(new java.awt.Color(251, 252, 252));

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Algoritmo");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 20, 117, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("de");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 50, 28, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Euclides");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 80, 110, 32);

        instructions.setEditable(false);
        jScrollPane1.setViewportView(instructions);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 150, 280);

        switchToDijkstra.setText("Cambiar a Dijkstra");
        switchToDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToDijkstraActionPerformed(evt);
            }
        });
        jPanel2.add(switchToDijkstra);
        switchToDijkstra.setBounds(20, 460, 126, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Instrucciones de uso:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 140, 116, 16);

        variables.setText("Ingrese un número ");

        addbutton.setText("Aceptar");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        consoleArea.setColumns(20);
        consoleArea.setRows(5);
        consoleArea.setEnabled(false);
        jScrollPane2.setViewportView(consoleArea);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout canvasEuclidesLayout = new javax.swing.GroupLayout(canvasEuclides);
        canvasEuclides.setLayout(canvasEuclidesLayout);
        canvasEuclidesLayout.setHorizontalGroup(
            canvasEuclidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canvasEuclidesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(canvasEuclidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(canvasEuclidesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(variables, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(canvasEuclidesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        canvasEuclidesLayout.setVerticalGroup(
            canvasEuclidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(canvasEuclidesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(canvasEuclidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(canvasEuclidesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(canvasEuclides);
        canvasEuclides.setBounds(-10, -10, 700, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        try {
            if(this.a == 0 && this.b == 0){
                this.a = Integer.parseInt(this.variables.getText().trim());
                this.consoleArea.append("\n\n usuario: Para el valor de 'a' usare: " + this.a);
                this.consoleArea.append("\n\n Euclides: ingresa el valor de 'b':");
                this.variables.setText("");
            }else if(this.a != 0 && this.b == 0){
                this.b = Integer.parseInt(this.variables.getText().trim());
                this.consoleArea.append("\n\n usuario: Para el valor de 'b' usare: " + this.b);
            }
            if(this.a != 0 && this.b != 0){
                this.addbutton.enable(false);
                this.consoleArea.append("\n\n Euclides: Perfecto, operare el MCD de A: " + this.a + " y B:" + this.b + "\n\n");

                do{
                    if(this.aux != 0){
                        this.mod = (this.aux == -1) ? a%b : b%this.aux;
                        this.aux = this.mod;    
                        this.consoleArea.append("\n Euclides: "+ this.a +"%" + this.b + " Residuo: " + this.mod);
                    }
                }while(this.aux != 0);

                this.consoleArea.append("\n\n El MCD DE: " + this.a + " y " + this.b + " es: " + String.valueOf(this.euclides.euclidesAlgorithm(this.a, this.b)));
            }
        } catch (Exception e) {
            this.consoleArea.append("\n\n Euclides: POR FAVOR INGRESA UN VALOR VALIDO!");
        }
        
    }//GEN-LAST:event_addbuttonActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        try {
            int reset = JOptionPane.showConfirmDialog(null,"¿Desea probar con dos nuevos numeros?");
            if(reset == 0){
                initialize();
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_LimpiarActionPerformed

    private void switchToDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToDijkstraActionPerformed
        DijkstraGui dijkstraGui = new DijkstraGui();
        dijkstraGui.show();
        dispose();
    }//GEN-LAST:event_switchToDijkstraActionPerformed

    private void initialize(){
        this.consoleArea.setText("");
        this.consoleArea.setText("Euclides: Por favor ingresa un valor para A y para B cuando sea requerido: \n Ingresa el valor de 'a': ");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton addbutton;
    private javax.swing.JPanel canvasEuclides;
    private javax.swing.JTextArea consoleArea;
    private javax.swing.JTextPane instructions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton switchToDijkstra;
    private javax.swing.JTextField variables;
    // End of variables declaration//GEN-END:variables
}
